cse403-fitquest/fitquest

eslint.config.mjs
pull_request_template.md
reports/20241010.md
team-resources.md

Added:
- Weekly report markdown file
- Team resources markdown file
- PR template file attempt

Add Markdown docs and try add PR template

---

pull_request_template.md
team-resources.md

Add PR title policy in team resources file
- PR title policy in team resources md file

Add PR title policy in team resources file

---

README.md

Update roadmap and tech and add contributor roles in README
- Task breakdown for most sections in roadmap section
- Add Zustand to tech section
- Add roles for each team member in contributor section

Update roadmap and tech, add contributor roles in README

---

team-resources.md

Add links for architecture & design document and Figma UI in team resources file
- Add link for architecture & design doc
- Add link for Figma UI design

Add more doc links in team resources file

---

README.md

Add team resources link in README
- Add team resources link in README

Add team resources link in README

---

README.md

Update app description and roadmap in README
- Change description from users' journey to users' progress (progress seems more mechanical and less romantic)
- Add implementing Social screen as part of Roadmap

Update app description and roadmap in README

---

pull_request_template.md
reports/20241010.md
reports/20241017.md

Add October 17 weekly report
- Filled in last week's goals
- Filled in current week's progress and issues
- Filled in next team meeting agenda
- Filled in progress and issues and next week's plans and goals for Afuza

Add October 17 weekly report

---

reports/20241017.md

Filled out my section of the weekly report
- Updated my report for week of 10/17

Weekly Report Update 17th October Steven

---

.github/workflows/lint.yml
.github/workflows/tests.yml
components/FQButton.tsx
components/FQTextInput.tsx
package-lock.json
package.json
reports/20241010.md
reports/20241017.md
reports/20241024.md
reports/base.md
tests/components/__tests__/FQButton.test.tsx
tests/components/__tests__/FQTextInput.test.tsx

Update 17th October weekly report for Afuza and add CI script to enforce linting
- Made changes to Afuza's progress for 17th October weekly report
- Added weekly report template and made October 24th weekly report template
- Added GH actions workflow to lint code on PR

Update 17th October weekly report for Afuza and add CI script to enforce linting

---

store/onboarding.ts

Create Onboarding store to save user answers in the Onboarding flow
- Create Onboarding store

Create Onboarding store

---

app/(tabs)/shop.tsx
components/FQModal.tsx
reports/20241024.md
tailwind.config.js
tests/components/__tests__/FQModal.test.tsx
tests/utils/__tests__/item.test.ts
types/item.ts
utils/item.ts

Implement frontend for shop screen
- Implement frontend for shop screen
- Create FQModal reusable component
- Create unit tests for item-related utility functions and FQModal
- Update Afuza's part of weekly report

Implement frontend for shop screen

---

app/(tabs)/profile.tsx
tailwind.config.js
tsconfig.json

Added the Profile page with user stats, equipped items display, workout history visualization, and settings modal. The page includes mock data for initial development.
- Created Profile screen with user information display
- Added equipment grid showing user's items
- Implemented settings modal with privacy toggles and account management
- Added workout history visualization with weekly stats
- Integrated sign-out functionality (will crash the app, however)
- Added item inspection modal for equipment management

Initial implementation of profile screen

---

README.md
documentation/devDoc.md
documentation/userDoc.md

Add initial user and developer documentation according to the [Documentation Spec](https://courses.cs.washington.edu/courses/cse403/24au/project/06_documentation.html).
- Add user documentation according to spec
- Add developer documentation according to spec

Add initial user and developer documentation

---

app/(tabs)/_layout.tsx
components/Collapsible.tsx
hooks/useThemeColor.ts
package-lock.json
package.json

Fix color constant error and installation dependencies
- For some reason, changes to the Colors.ts file in /constants is not tracked by github, making it such that every new clone gets an incorrect import to colors.ts instead of Colors.ts. Now fixed to just be named Colors.ts like how it was originally
- When installing dependencies, encountered errors related to ajv and tailwind. So they are now install appropriately and now the app works perfectly fine on an android emulator

Fix color constant error and installation dependencies

---

app/(tabs)/profile.tsx
services/user.ts

Enable users to edit their username, height, and weight on their profile. Display the user's gold balance and update the settings modal UI accordingly.
- Added input validation for username, height and weight fields
- Displayed the user's gold balance on the profile screen
- Implemented updateUserProfile function to handle profile updates in Firestore

added user data editing in profile settings

---

services/social.ts
tests/services/__tests__/social.test.ts

Create initial tests for social services
- Test getUserFriends
- Test createUserFriends

Test: Create initial tests for social services

---

services/item.ts
tests/services/__tests__/item.test.ts
types/item.ts
types/shop.ts

Create tests for item services
- Test fetchItems
- Test setItemsInDB
- Test purchaseItem

Test: Create tests for item services

---

pull_request_template.md
reports/20241107.md
reports/20241114.md

Update weekly report for November 14th for Afuza
- Add Afuza's goals for next week
- Add Report option to PR template's affect options

Update weekly report for November 14th for Afuza & PR Template

---

.github/ISSUE_TEMPLATE/bug_report.md

Update bug_report.md to add desktop specifications
- Update bug_report.md to add desktop specifications

Update bug_report.md to add desktop specifications

---

README.md
documentation/devDoc.md
documentation/userDoc.md

Fix dev guidelines and user doc to include latest instructions
- Add clearer instructions to run tests
- Simplify start command from npx expo start -c to just npm start
- Add android emulator setup links

Fix documentation to include latest instructions

---

app/(tabs)/workout.tsx
reports/20241114.md
services/workout.ts
tailwind.config.js

Implement exp gain modal display after finish workout and decrease exp gain from 1000x to 500x. 
- Implement exp gain modal display after finish workout
- Decrease exp gain from 1000x to 500x.

Implement exp gain modal display after finish workout

---

reports/20241121.md

Update Nov 14 weekly report for Afuza and create Nov 21 report 
- Update Nov 14 weekly report for Afuza
- Add Nov 21 weekly report

Update Nov 14 weekly report for Afuza and create Nov 21 report 

---

app/(tabs)/workout.tsx

Allows users to delete their saved templates
- added remove button
- added confirmation screen
no
workout.tsx

Workoutremove

---

app/(tabs)/_layout.tsx
app/(tabs)/workout.tsx
constants/user.ts
package-lock.json
services/workout.ts
types/user.ts
types/workout.ts
utils/workout.ts

added backend within workout
- added workout schema
- added exercise schema 
- added exercise tags and set types to schema
- User has savedWorkouts field now
- workout - types, utils, constants, services
- user - baseuser, type

Workoutsbackend

---

app/(tabs)/profile.tsx
app/(tabs)/workout.tsx
app/(workout)/add-exercises.tsx
app/(workout)/new-workout.tsx
app/_layout.tsx
services/workout.ts
store/workout.ts

Integrate async storage for active workout so that users can exit the app or go to other screens while still retaining their current active workout. They can go back to their workout through the RESUME workout button in the workout screen.
- Users can go out of the workout screen and have their workout persisted (via device storage)
- Users can come back to the workout screen and resume their workout.

Feat: Integrate async storage for active workout

---

reports/20241010.md
reports/20241017.md
reports/20241024.md
reports/20241031.md
reports/20241107.md
reports/20241114.md
reports/20241121.md

Brief description of your changes
- Made updates to my sections in the weekly reports

updated weekly reports

---

app/(tabs)/profile.tsx
services/user.ts
tests/services/__tests__/user.test.ts

Added test suite for updateUserProfile function in user service
- Added test coverage for updateUserProfile scenarios (partial updates, empty updates, errors)

Add tests for updateUserProfile, multiple scenarios

---

constants/user.ts
types/user.ts

Update user object to have activeWorkoutMinutes
- Update user object to have activeWorkoutMinutes

Feat: Update user object to have activeWorkoutMinutes

---

app/(tabs)/_layout.tsx
app/(tabs)/social.tsx
app/_layout.tsx
components/FQModal.tsx
services/quest.ts
services/social.ts
services/user.ts
store/social.ts
types/social.ts
utils/general.ts

Display friend information (sprite, quest name, last workout date) in social screen and refactor the social system to not store static data and instead store requests and friends as user ids (string). On loading the app or refreshing the social screen, this lets us get the most up to date information on our friends.
- Display friend information in social screen (sprite, quest name, last workout date)
- Refactor social system

Feat: Display friend information in social screen

---

app/(tabs)/quest.tsx
app/fight.tsx
components/AnimatedSprite.tsx
utils/sprite.ts

Brief description of your changes
Added 3rd quest to Active Quest Board
- Change 1
Added 3rd quest to Active Quest Board

added 3rd quest

---

reports/20241128.md
reports/20241208.md

Brief description of your changes
added the final 2 weekly reports
- added the final 2 weekly reports

added 2 reports for 11/28 and 12/8

---

app/(onboarding)/02-before-begin.tsx
app/(onboarding)/03-frequency.tsx
app/(tabs)/profile.tsx
app/(tabs)/quest.tsx
app/(tabs)/shop.tsx
constants/workout.ts
tests/integration/shop/__tests__/shop.test.tsx
utils/item.ts

Fix bugs related to incorrect large potion count in shop, lack of weights and nonsensical workout templates, and incorrect text when abandoning a quest
- Fix bug where large potion amount is incorrect in shop
- Add weights to all suggested workout templates and changed 'Heart Health' template
- Change confirmation text when abandoning quest to ensure that progress is saved and not reset

Fix: Bug for large potion in shop, workout template, abandon quest

---

app/(tabs)/workout.tsx
app/(workout)/workout-template.tsx
app/fight.tsx
pull_request_template.md
services/item.ts
services/social.ts
services/user.helper.ts
services/user.ts
services/workout.ts

Implement workout history in workout screen (last section) to display past workouts. It is only used for displaying, it cannot be interacted with (edited nor deleted). Fixed turn order bug in fight screen.
- Implement workout history
- Fixed turn order bug in fight screen

Feat: Workout history and bug fixes

---

reports/20241010.md
reports/20241017.md
reports/20241024.md
reports/20241031.md
reports/20241107.md
reports/20241114.md
reports/20241121.md
reports/20241128.md
reports/20241208.md

made my report changes 
- reports added
- no
reports

Dom's reports

---

app/(tabs)/profile.tsx
app/(tabs)/quest.tsx

Fix predeploy bugs
- Fix signing out giving error
- Fix item type in profile screen not parsed into proper format
- Implement unequip stat difference

Fix: Predeploy bugs

---

app/(tabs)/profile.tsx
app/(tabs)/workout.tsx
app/(workout)/add-exercises.tsx
app/(workout)/edit-workout-template.tsx
app/(workout)/new-workout.tsx
app/(workout)/workout-template.tsx
constants/user.ts
package-lock.json
package.json
services/user.ts
tests/integration/profile/__tests__/profile.test.tsx
tests/integration/workout/__tests__/new-workout.test.tsx
types/user.ts

Hotfix to not use old uuid library
- Change 1

Hotfix to not use old uuid library

---

README.md
app/(workout)/new-workout.tsx
documentation/userDoc.md
package-lock.json
package.json
services/workout.ts

Hotfix: Fix converting from seconds to minutes when finishing a workout
- Fix converting from seconds to minutes when finishing a workout

Hotfix: Fix converting from seconds to minutes
